"""add user_id to audit_logs

Revision ID: a374cd5ac496
Revises: 60dd286bb859
Create Date: 2026-06-01 17:40:01.244254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a374cd5ac496'
down_revision: Union[str, Sequence[str], None] = '60dd286bb859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'user_id')
    # ### end Alembic commands ###
